name: Build Android Kernel SM8250

on:
  workflow_dispatch: # 允许手动点击按钮触发编译

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache flex glibc-source libelf-dev libssl-dev libio-pty-perl git nano visualvm cpio libncurses5-dev libncursesw5-dev xz-utils
   
    - name: Download Proton Clang Toolchain
      run: |
        URL=$(echo "aHR0cHM6Ly9naXRodWIuY29tL2tkcmFnMG4vcHJvdG9uLWNsYW5nLmdpdA==" | base64 -d)
        git clone --depth=1 "$URL" $GITHUB_WORKSPACE/clang-bin
        echo "$GITHUB_WORKSPACE/clang-bin/bin" >> $GITHUB_PATH

    - name: Setup Build Environment Variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV

    - name: Run Build
      run: |
        # 1. 生成配置文件（加入 CC=clang 强制让 Kconfig 识别 Clang 编译器）
        make O=out vendor/kona-perf_defconfig CC=clang

        # 2. 开始编译（使用完整的 LLVM=1 参数，停用传统的 GCC 依赖）
        make -j$(nproc --all) O=out CC=clang LLVM=1 LLVM_IAS=1

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Kernel-Image
        path: out/arch/arm64/boot/Image
